---
Resources:
  LambdaFunc:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::302394221410:role/cflambda-role
      Runtime: python3.8
      Code:
        S3Bucket: "demoforcf"
        S3Key: "lambda_function.zip"
      FunctionName: "LambdaForMacie"
